### ISSUE TITLE
Sprite bug? or missing files/settings?

### ISSUE THREAD

**Issue by Ausfragezeichen** [Schiggebam/FightOfAIs3#28]
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 237, in 'calling callback function'
  File "C:\Program Files\Python38\lib\site-packages\pyglet\window\win32\__init__.py", line 712, in f
    result = event_handler(msg, wParam, lParam)
  File "C:\Program Files\Python38\lib\site-packages\pyglet\window\win32\__init__.py", line 933, in _event_mousemove
    self.dispatch_event('on_mouse_motion', x, y, dx, dy)
  File "C:\Program Files\Python38\lib\site-packages\pyglet\window\__init__.py", line 1333, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "C:\Program Files\Python38\lib\site-packages\pyglet\event.py", line 420, in dispatch_event
    raise e
  File "C:\Program Files\Python38\lib\site-packages\pyglet\event.py", line 415, in dispatch_event
    if getattr(self, event_type)(*args):
  File "C:/Users/muhah/PycharmProjects/FightOfAIs3/src/game.py", line 261, in on_mouse_motion
    self.hi.handle_mouse_motin(int(x), int(y))
  File "C:\Users\muhah\PycharmProjects\FightOfAIs3\src\ui\human.py", line 196, in handle_mouse_motin
    xx = h.ground.sprite.center_x
AttributeError: 'NoneType' object has no attribute 'ground'

**Comment by Schiggebam** [comment]
thanks. das ist auf jeden Fall ein Bug
